base:
  - autoload:
      add: True
      path: $HOME/.autoload
      stow: autoload
  - nvim:
      add: True
      path: $HOME/.config/nvim
      stow: nvim
  - tmux:
      add: True
      path: $HOME
      stow: tmux
  - tmuxinator:
      add: True
      path: $HOME/.tmuxinator
      stow: tmuxinator
  - spacemacs:
      add: True
      path: $HOME
      stow: spacemacs

mac:
  - zprezto:
      add: True
      path: $HOME
      stow: mac__zprezto


linux-uberspace:
  - zprezto:
      add: True
      path: $HOME
      stow: linux__uberspace_zprezto
  - nvim:
      add: False
  - tmux:
      add: False
  - tmuxinator:
      add: False

linux-work:
  - zprezto:
      add: True
      path: $HOME
      stow: linux__work_zprezto


