base:
  - autoload:
      add: True
      path: $HOME/.autoload
      stow: autoload
  - nvim:
      add: True
      path: $HOME/.config/nvim
      stow: nvim
  - tmux:
      add: True
      path: $HOME
      stow: tmux
  - tmuxinator:
      add: True
      path: $HOME/.tmuxinator
      stow: tmuxinator
  - spacemacs:
      add: True
      path: $HOME/.spacemacs.d
      stow: .spacemacs.d

mac:
  - zprezto:
      add: True
      path: $HOME
      stow: mac__zprezto

linux-work:
  - zprezto:
      add: True
      path: $HOME
      stow: linux__work_zprezto

linux-work-docker:
  - tmuxinator:
      add: False
  - tmux:
      add: False
  - nvim:
      add: False
  - autoload:
      add: False


linux-uberspace:
  - zprezto:
      add: True
      path: $HOME
      stow: linux__uberspace_zprezto
  - nvim:
      add: False
  - tmux:
      add: False
  - tmuxinator:
      add: False
